services:
  - type: web
    name: task-manager-api
    env: node
    plan: free
    buildCommand: "if [ -d backend ]; then cd backend && npm install; else echo 'Backend directory not found' && exit 1; fi"
    startCommand: "cd backend && npm start"
    rootDir: "./"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://showcase:showcasejha@cluster0.stusub5.mongodb.net/taskmanager?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: cabcdefghkdkkd
      - key: CORS_ORIGIN
        value: https://task-manager-rouge-eta.vercel.app